"use client";
import {useEffect,useState} from 'react';
import {apiClient} from '@/lib/api';
import {useAuthStore} from '@/store/authStore';
import {IntegrationForm} from '@/components/ui/IntegrationForm';
import {ErrorState} from '@/components/ui/ErrorState';
const configs={
 attendance:{title:'Attendance',endpoint:'/api/attendance',columns:['employeeName','date','checkIn','checkOut','workedHours','status'],fields:[{name:'employeeId',label:'Employee',source:'employees',required:true},{name:'date',label:'Date',type:'date',required:true},{name:'checkIn',label:'Check in (UTC)',type:'datetime-local'},{name:'checkOut',label:'Check out (UTC)',type:'datetime-local'},{name:'breakMinutes',label:'Break minutes',type:'number',defaultValue:0,min:0},{name:'notes',label:'Notes'}]},
 requests:{title:'Time Off Requests',endpoint:'/api/timeoff/requests',columns:['employeeName','typeName','fromDate','toDate','duration','status'],fields:[{name:'employeeId',label:'Employee',source:'employees',required:true},{name:'timeOffTypeId',label:'Leave type',source:'types',required:true},{name:'fromDate',label:'From',type:'date',required:true},{name:'toDate',label:'To',type:'date',required:true},{name:'reason',label:'Reason',required:true}]},
 types:{title:'Time Off Types',endpoint:'/api/timeoff/types',columns:['name','code','unit','isPaid','requiresAllocation'],fields:[{name:'name',label:'Name',required:true},{name:'code',label:'Code',required:true},{name:'unit',label:'Unit',options:['DAYS','HOURS'],defaultValue:'DAYS',required:true},{name:'isPaid',label:'Paid leave',options:['true','false'],defaultValue:'true'},{name:'requiresAllocation',label:'Requires allocation',options:['true','false'],defaultValue:'true'}]},
 allocations:{title:'Leave Allocations',endpoint:'/api/timeoff/allocations',columns:['employeeName','typeName','allocatedAmount','takenAmount','remainingAmount','status'],fields:[{name:'employeeId',label:'Employee',source:'employees',required:true},{name:'timeOffTypeId',label:'Leave type',source:'types',required:true},{name:'periodStart',label:'Valid from',type:'date',required:true},{name:'periodEnd',label:'Valid until',type:'date',required:true},{name:'allocatedAmount',label:'Days / hours to allocate',type:'number',min:0,required:true}]},
};
const display=v=>v==null?'—':typeof v==='boolean'?(v?'Yes':'No'):String(v).replace('T',' ').replace('.000Z','');
export default function OperationsPage({module}) {
 const c=configs[module],{user}=useAuthStore(),isHR=user?.role!=='EMPLOYEE';
 const [rows,setRows]=useState([]),[options,setOptions]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{const employeeId=new URLSearchParams(window.location.search).get('employeeId')||undefined;setRows((await apiClient.get(c.endpoint,{params:{limit:200,employeeId}})).data.data);}catch(e){setError(e.response?.data?.message||'Unable to load records');}finally{setLoading(false);}}
 useEffect(()=>{load();Promise.all([apiClient.get('/api/employees?limit=200'),apiClient.get('/api/timeoff/types?limit=200')]).then(([e,t])=>setOptions({employees:e.data.data.map(x=>({value:x.id,label:x.name})),types:t.data.data.map(x=>({value:x.id,label:x.name}))})).catch(()=>{});},[module]);
 if(!isHR&&module==='types')return <p>Only HR can manage leave types.</p>;
 const fields=c.fields.filter(f=>isHR||f.name!=='employeeId').map(f=>({...f,...(f.source?{options:options[f.source]||[]}:{})}));if(editing?.id&&module==='attendance')fields.push({name:'reason',label:'Reason for correction',required:true});
 async function save(values){setSaving(true);try{const b={...values};for(const k of ['isPaid','requiresAllocation'])if(k in b)b[k]=b[k]==='true';if(!isHR)b.employeeId=user.employeeId;for(const k of ['checkIn','checkOut'])if(b[k])b[k]=b[k]+'Z';await apiClient[editing.id?'put':'post'](c.endpoint+(editing.id?'/'+editing.id:''),b);setEditing(null);setMessage('Saved successfully');await load();}finally{setSaving(false);}}
 async function decide(row,status){setSaving(true);try{await apiClient.put(c.endpoint+'/'+row.id,{status});setMessage('Request '+status.toLowerCase());await load();}catch(e){setError(e.response?.data?.message||'Unable to process request');}finally{setSaving(false);}}
 return <div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">{c.title}</h1>{(isHR||['requests','attendance'].includes(module))&&<button className="rounded-lg bg-violet-600 px-4 py-2" onClick={()=>setEditing({})}>New record</button>}</div>{module!=='attendance'&&<nav className="flex gap-5"><a href="/time-off">Requests</a>{isHR&&<a href="/time-off/types">Types</a>}<a href="/time-off/allocations">Allocations & balances</a></nav>}{message&&<p role="status" className="text-emerald-400">{message}</p>}{editing&&<section className="rounded-xl border border-slate-700 bg-slate-950 p-6"><IntegrationForm key={editing.id||'new'} fields={fields} initialData={Object.fromEntries(Object.entries(editing).map(([k,v])=>[k,typeof v==='string'&&v.includes('T')?v.slice(0,k==='date'?10:16):v]))} onSubmit={save} onCancel={()=>setEditing(null)} isLoading={saving}/></section>}{error&&<ErrorState title="Unable to complete request" message={error} onRetry={load}/>}<div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{c.columns.map(k=><th className="p-3" key={k}>{k.replace(/([A-Z])/g,' $1')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-800">{c.columns.map(k=><td className="p-3" key={k}>{display(r[k])}</td>)}<td className="space-x-3">{isHR&&module==='attendance'&&<button onClick={()=>setEditing(r)}>Correct</button>}{isHR&&module==='requests'&&r.status==='PENDING'&&<><button disabled={saving} onClick={()=>decide(r,'APPROVED')}>Approve</button><button disabled={saving} onClick={()=>decide(r,'REJECTED')}>Reject</button></>}</td></tr>)}</tbody></table>{loading?<p className="p-6">Loading…</p>:!rows.length&&<p className="p-6 text-slate-400">No records yet.</p>}</div></div>;
}
