"use client";
import {useEffect,useState} from 'react';
import {apiClient} from '@/lib/api';
import {useAuthStore} from '@/store/authStore';
import {BarChart,Bar,LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
export default function LiveDashboard(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[filters,setFilters]=useState({period:'',department:'',employeeType:''});const {user}=useAuthStore();const payroll=['ADMIN','HR_PAYROLL_USER','HR_PAYROLL_MANAGER'].includes(user?.role);
 async function load(){setError('');try{setData((await apiClient.get('/api/dashboard',{params:filters})).data.data);}catch(e){setError(e.response?.data?.message||'Unable to load dashboard');}}
 useEffect(()=>{load();},[filters.period,filters.department,filters.employeeType]);
 return <div className="space-y-6"><h1 className="text-3xl font-bold">{user?.name}&apos;s Dashboard</h1><div className="flex flex-wrap gap-3"><input aria-label="Period" type="month" className="rounded-lg bg-slate-900 p-3" value={filters.period} onChange={e=>setFilters({...filters,period:e.target.value})}/><input aria-label="Department" placeholder="Department" className="rounded-lg bg-slate-900 p-3" value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})}/><select aria-label="Employee type" className="rounded-lg bg-slate-900 p-3" value={filters.employeeType} onChange={e=>setFilters({...filters,employeeType:e.target.value})}><option value="">All employee types</option>{['FULL_TIME','PART_TIME','CONTRACT','INTERN'].map(x=><option key={x}>{x}</option>)}</select><button onClick={load}>Refresh</button></div>{error&&<p role="alert" className="text-rose-400">{error}</p>}{!data&&!error&&<p>Loading…</p>}{data&&<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Workforce',data.kpis.totalWorkforce],['Present / Late',`${data.attendanceOverview.present} / ${data.attendanceOverview.late}`],['Pending leave requests',data.pendingTimeOffRequests],['Leave balance',data.leaveBalance],...(payroll?[['Net salary paid',`₹${Number(data.kpis.totalNetSalaryPaid).toLocaleString('en-IN')}`],['Payslips generated',data.kpis.payslipsGenerated],['Average salary',`₹${Number(data.kpis.averageSalary).toLocaleString('en-IN')}`]]:[])].map(([label,value])=><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5" key={label}><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-2xl font-bold">{value}</p></section>)}</div>{payroll&&<div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-slate-800 p-5"><h2>Salary cost by department</h2><ResponsiveContainer width="100%" height={250}><BarChart data={data.salaryByDepartment}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="salary" fill="#7c3aed"/></BarChart></ResponsiveContainer></section><section className="rounded-xl border border-slate-800 p-5"><h2>Monthly net salary</h2><ResponsiveContainer width="100%" height={250}><LineChart data={data.monthlySalaryTrend}><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="netSalary" stroke="#06b6d4"/></LineChart></ResponsiveContainer></section></div>}<section className="rounded-xl border border-slate-800 p-5"><h2 className="text-lg font-semibold">Attention needed</h2><p>Missing checkouts: {data.attendanceOverview.missingCheckouts} · Corrected records: {data.attendanceOverview.manualEdits}</p>{data.warnings.map(w=><p className="mt-2 text-amber-300" key={w.id}>{w.message}</p>)}</section><nav className="flex flex-wrap gap-5"><a href="/attendance">Review attendance</a><a href="/time-off">Time off requests</a>{payroll&&<a href="/payroll/payruns">Manage payruns</a>}</nav></>}</div>;
}
