"use client";
import {useEffect,useState} from 'react';
import {History,ShieldCheck,UserPlus,Users} from 'lucide-react';
import {apiClient} from '@/lib/api';
import {useAuthStore} from '@/store/authStore';
import {IntegrationForm} from '@/components/ui/IntegrationForm';
import {Badge} from '@/components/ui/Badge';

export default function Page(){
 const {user}=useAuthStore();
 const [users,setUsers]=useState([]),[employees,setEmployees]=useState([]),[logs,setLogs]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){try{setError('');const [u,e,a]=await Promise.all([apiClient.get('/api/admin/users'),apiClient.get('/api/employees?limit=50'),apiClient.get('/api/admin/audit')]);setUsers(u.data.data);setEmployees(e.data.data);setLogs(a.data.data);}catch(e){setError(e.response?.data?.message||'Unable to load administration');}}
 useEffect(()=>{if(user?.role==='ADMIN')load();},[user]);
 if(user?.role!=='ADMIN')return <div className="erp-card rounded-xl p-8 text-center text-sm text-slate-600">Administrator access required.</div>;
 async function createUser(values){setBusy(true);setMessage('');try{await apiClient.post('/api/admin/users',{...values,employeeId:values.employeeId||undefined});setMessage('User account created successfully.');await load();}finally{setBusy(false);}}
 return <div className="space-y-6">
  <header className="erp-page-header"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">System administration</p><h1 className="mt-1 flex items-center gap-2 text-2xl font-bold text-slate-900"><ShieldCheck className="h-6 w-6 text-blue-700"/>User access</h1><p className="mt-1 text-sm text-slate-500">Create role-based accounts and review recorded system actions.</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-center"><strong className="block text-xl text-slate-900">{users.length}</strong><span className="text-xs text-slate-500">Users</span></div><div className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-center"><strong className="block text-xl text-slate-900">{logs.length}</strong><span className="text-xs text-slate-500">Audit events</span></div></div></header>
  {error&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{message&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}
  <section className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
   <article className="erp-card rounded-xl p-5"><div className="mb-5 flex items-center gap-3"><div className="rounded-lg bg-blue-50 p-2 text-blue-700"><UserPlus className="h-5 w-5"/></div><div><h2 className="font-bold text-slate-900">Create user</h2><p className="text-xs text-slate-500">Assign a role and link employee accounts.</p></div></div><IntegrationForm fields={[{name:'name',label:'Name',required:true},{name:'email',label:'Email',type:'email',required:true},{name:'password',label:'Password (at least 8 characters)',type:'password',required:true},{name:'role',label:'Role',options:['EMPLOYEE','HR_MANAGER','HR_PAYROLL_USER','HR_PAYROLL_MANAGER','ADMIN'],required:true},{name:'employeeId',label:'Linked employee',options:employees.map(e=>({value:e.id,label:`${e.name} · ${e.employeeCode}`}))}]} isLoading={busy} onSubmit={createUser} submitLabel="Create user"/></article>
   <article className="erp-table-wrap"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><Users className="h-5 w-5 text-blue-700"/><div><h2 className="font-bold text-slate-900">Registered users</h2><p className="text-xs text-slate-500">Authentication accounts and assigned access.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Linked employee</th><th className="px-5 py-3">Created</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map(item=><tr key={item.id}><td className="px-5 py-4"><strong className="block text-slate-800">{item.name}</strong><span className="text-xs text-slate-500">{item.email}</span></td><td className="px-5 py-4"><Badge>{item.role.replaceAll('_',' ')}</Badge></td><td className="px-5 py-4 text-slate-600">{employees.find(employee=>employee.id===item.employeeId)?.name||'—'}</td><td className="px-5 py-4 text-slate-500">{new Date(item.createdAt).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></article>
  </section>
  <section className="erp-table-wrap"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><History className="h-5 w-5 text-blue-700"/><div><h2 className="font-bold text-slate-900">Audit history</h2><p className="text-xs text-slate-500">Latest user and business-record activity.</p></div></div><div className="max-h-[34rem] overflow-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="sticky top-0"><tr><th className="px-5 py-3">Date &amp; time</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Entity</th><th className="px-5 py-3">Record ID</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map(log=><tr key={log.id}><td className="px-5 py-4 text-slate-500">{new Date(log.createdAt).toLocaleString('en-IN')}</td><td className="px-5 py-4 font-semibold text-slate-800">{log.user?.name||'System'}</td><td className="px-5 py-4"><Badge>{log.action}</Badge></td><td className="px-5 py-4 text-slate-700">{log.entityType}</td><td className="px-5 py-4 font-mono text-xs text-slate-500">{log.entityId}</td></tr>)}</tbody></table></div></section>
 </div>;
}
