ALTER TABLE `TimeOffType` ADD COLUMN `isPaid` BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE `Payrun` ADD COLUMN `version` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `paymentDate` DATETIME(3) NULL;
ALTER TABLE `Payslip` ADD COLUMN `snapshot` JSON NULL;
