/**
 * PeoplePay360 Data Models & Contract References
 * Pure JavaScript module providing standard enum constants and contract definitions
 * for Navaneeth (Frontend), Mohith (Backend), and Poshika (Database).
 */

export const USER_ROLES = {
  EMPLOYEE: "EMPLOYEE",
  HR_MANAGER: "HR_MANAGER",
  HR_PAYROLL_USER: "HR_PAYROLL_USER",
  HR_PAYROLL_MANAGER: "HR_PAYROLL_MANAGER",
  ADMIN: "ADMIN",
};

export const EMPLOYEE_STATUS = {
  ACTIVE: "ACTIVE",
  NOTICE_PERIOD: "NOTICE_PERIOD",
  TERMINATED: "TERMINATED",
};

export const CONTRACT_STATUS = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  ENDED: "ENDED",
};

export const ATTENDANCE_STATUS = {
  PRESENT: "PRESENT",
  LATE: "LATE",
  ABSENT: "ABSENT",
  EXCEPTION: "EXCEPTION",
};

export const TIME_OFF_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const PAYRUN_STATUS = {
  DRAFT: "DRAFT",
  COMPUTED: "COMPUTED",
  VALIDATED: "VALIDATED",
  PAID: "PAID",
};

export const PAYSLIP_STATUS = {
  DRAFT: "DRAFT",
  COMPUTED: "COMPUTED",
  VALIDATED: "VALIDATED",
  PAID: "PAID",
};

export const SALARY_RULE_CATEGORIES = {
  BASIC: "BASIC",
  ALLOWANCE: "ALLOWANCE",
  GROSS: "GROSS",
  DEDUCTION: "DEDUCTION",
  NET: "NET",
  REIMBURSEMENT: "REIMBURSEMENT",
};

export const WARNING_TYPES = {
  MISSING_BANK_DETAILS: "MISSING_BANK_DETAILS",
  MISSING_PAN: "MISSING_PAN",
  DUPLICATE_PAYSLIP: "DUPLICATE_PAYSLIP",
  NO_ACTIVE_CONTRACT: "NO_ACTIVE_CONTRACT",
  OVERLAPPING_CONTRACT: "OVERLAPPING_CONTRACT",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
};
