import { requireAuth, isHr } from "@/lib/auth";
import { failure, handleError, success } from "@/lib/api";
import { NotFoundError } from "@/lib/errors";
import { audit } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
const schema = z.object({ checkIn: z.coerce.date().nullable().optional(), checkOut: z.coerce.date().nullable().optional(), notes: z.string().optional() }).refine((v) => !v.checkIn || !v.checkOut || v.checkIn <= v.checkOut, { message: "checkOut must be after checkIn", path: ["checkOut"] });
export async function GET(request, { params }) { try { const user = await requireAuth(); const result = await prisma.attendanceRecord.findUnique({ where: { id: (await params).id }, include: { employee: true } }); if (!result) throw new NotFoundError("Attendance record not found"); if (!isHr(user.role) && result.employeeId !== user.employee?.id) return failure("You can only view your own attendance", 403); return success(result); } catch (error) { return handleError(error); } }
export async function PUT(request, { params }) { try { const user = await requireAuth(); const id = (await params).id; const existing = await prisma.attendanceRecord.findUnique({ where: { id } }); if (!existing) throw new NotFoundError("Attendance record not found"); if (!isHr(user.role) && existing.employeeId !== user.employee?.id) return failure("You can only update your own attendance", 403); const input = schema.parse(await request.json()); const workedHours = input.checkIn && input.checkOut ? Math.max(0, (input.checkOut - input.checkIn) / 3600000 - (existing.breakMinutes || 0) / 60) : null; const result = await prisma.attendanceRecord.update({ where: { id }, data: { checkIn: input.checkIn, checkOut: input.checkOut, workedHours, notes: input.notes, ...(isHr(user.role) ? { isManuallyCorrected: true, correctedByUserId: user.id } : {}) } }); if (isHr(user.role)) await audit(user.id, "ATTENDANCE_CORRECTED", "ATTENDANCE", id, { reason: input.notes }); return success(result, "Attendance updated"); } catch (error) { return handleError(error); } }
export async function DELETE(request, { params }) { try { const user = await requireAuth(); if (!isHr(user.role)) return failure("Only HR can delete attendance", 403); const id = (await params).id; await prisma.attendanceRecord.delete({ where: { id } }); await audit(user.id, "ATTENDANCE_DELETED", "ATTENDANCE", id); return success(null, "Attendance deleted"); } catch (error) { return handleError(error); } }
