import puppeteer from 'puppeteer';
import nodemailer from 'nodemailer';
import {handler,reply,check,MANAGERS,audit} from './http';
import {prisma} from '@/lib/prisma';
import {ownedPayslip,payslipView} from './payroll';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
function below1000(n){let s='';if(n>=100){s+=ones[Math.floor(n/100)]+' Hundred ';n%=100;}return (s+(n<20?ones[n]:tens[Math.floor(n/10)]+(n%10?' '+ones[n%10]:''))).trim();}
function inWords(value){let n=Math.round(Number(value));if(!n)return 'Rupees Zero Only';const parts=[];for(const [size,name] of [[10000000,'Crore'],[100000,'Lakh'],[1000,'Thousand']])if(n>=size){parts.push(below1000(Math.floor(n/size))+' '+name);n%=size;}if(n)parts.push(below1000(n));return 'Rupees '+parts.join(' ')+' Only';}
function html(p){const rows=items=>items.map(x=>`<tr><td>${escape(x.name)}</td><td>${escape(x.code)}</td><td class="money">₹${Number(x.amount).toLocaleString('en-IN',{minimumFractionDigits:2})}</td></tr>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:16mm}body{font:12px Arial;color:#172033}h1,h2{margin:0}.top{display:flex;justify-content:space-between;border-bottom:3px solid #6d28d9;padding-bottom:16px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:18px 0;padding:14px;background:#f5f3ff}.tables{display:grid;grid-template-columns:1fr 1fr;gap:18px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.money{text-align:right}.net{margin-top:20px;padding:16px;background:#ecfdf5;border:1px solid #10b981}.note{text-align:center;color:#64748b;margin-top:28px}.break{break-inside:avoid}</style></head><body><div class="top"><div><h1>${escape(p.company?.name||'PeoplePay360')}</h1><p>${escape(p.company?.address)}</p><p>Tax ID: ${escape(p.company?.taxId||'—')}</p></div><div><h2>PAYSLIP</h2><p>${escape(p.payslipNumber)}</p><p>${escape(String(p.month).padStart(2,'0'))}/${escape(p.year)}</p></div></div><div class="grid"><div><b>Employee:</b> ${escape(p.employeeName)}</div><div><b>Employee code:</b> ${escape(p.employeeCode)}</div><div><b>Department:</b> ${escape(p.department)}</div><div><b>Designation:</b> ${escape(p.jobPosition)}</div><div><b>Bank:</b> ${escape(p.bankName||'—')}</div><div><b>Account:</b> ${escape(p.bankAccountNumber||'—')}</div><div><b>PAN:</b> ${escape(p.panNumber||'—')}</div><div><b>UAN/PF:</b> ${escape(p.uanNumber||p.pfNumber||'—')}</div><div><b>Working days:</b> ${escape(p.workingDays)}</div><div><b>Worked days:</b> ${escape(p.workedDays??'Pending input')}</div></div><div class="tables break"><div><h3>Earnings</h3><table>${rows(p.earnings)}<tr><th>Gross earnings</th><th></th><th class="money">₹${p.grossEarnings.toLocaleString('en-IN')}</th></tr></table></div><div><h3>Deductions</h3><table>${rows(p.deductions)}<tr><th>Total deductions</th><th></th><th class="money">₹${p.totalDeductions.toLocaleString('en-IN')}</th></tr></table></div></div><div class="net break"><h2>Net transfer: ₹${p.netTransfer.toLocaleString('en-IN')}</h2><p>${inWords(p.netTransfer)}</p></div><p class="note">This is a computer generated document, hence no signature is required.</p></body></html>`;}
async function pdfFor(user,id){const p=payslipView(await ownedPayslip(user,id));const browser=await puppeteer.launch({headless:true,args:['--no-sandbox']});try{const page=await browser.newPage();await page.setContent(html(p),{waitUntil:'load'});return {buffer:await page.pdf({format:'A4',printBackground:true}),p};}finally{await browser.close();}}
export const pdfGET=handler(async({user,params})=>{const {buffer,p}=await pdfFor(user,params.id);return new Response(buffer,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${p.payslipNumber}.pdf"`,'Cache-Control':'private, no-store'}});});
function mailer(){check(process.env.SMTP_HOST&&process.env.SMTP_FROM,'Email delivery is not configured on this environment',503,'SMTP_NOT_CONFIGURED');check(!process.env.SMTP_USER||process.env.SMTP_PASS,'SMTP password is missing',503,'SMTP_NOT_CONFIGURED');const port=Number(process.env.SMTP_PORT||587);return nodemailer.createTransport({host:process.env.SMTP_HOST,port,secure:process.env.SMTP_SECURE==='true'||port===465,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:30000,pool:true,maxConnections:3,maxMessages:100,...(process.env.SMTP_USER?{auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}:{})});}
async function send(user,id,transport){const {buffer,p}=await pdfFor(user,id);check(p.employeeEmail,'Employee email is missing',422,'MISSING_EMAIL');await transport.sendMail({from:process.env.SMTP_FROM,to:p.employeeEmail,subject:`Payslip ${p.month}/${p.year}`,text:`Hello ${p.employeeName},\n\nYour PeoplePay360 payslip is attached.\n`,attachments:[{filename:`${p.payslipNumber}.pdf`,content:Buffer.from(buffer)}]});await prisma.payslip.update({where:{id},data:{emailedAt:new Date()}});return p;}
export const emailPOST=handler(async({user,params})=>{const transport=mailer();try{const p=await send(user,params.id,transport);await audit(prisma,user,'EMAIL','PAYSLIP',p.id);return reply({success:true,message:'Payslip sent successfully'});}finally{transport.close();}},MANAGERS);
export const bulkEmailPOST=handler(async({user,params})=>{const ids=(await prisma.payslip.findMany({where:{payrunId:params.id,status:'PAID'},select:{id:true}})).map(x=>x.id);check(ids.length,'No paid payslips are ready for delivery');const transport=mailer(),results=[];try{for(const id of ids){try{await send(user,id,transport);results.push({id,status:'SENT'});}catch(e){results.push({id,status:'FAILED',message:e.message});}}}finally{transport.close();}await audit(prisma,user,'BULK_EMAIL','PAYRUN',params.id,{results});return reply({sent:results.filter(r=>r.status==='SENT').length,failed:results.filter(r=>r.status==='FAILED').length,results});},MANAGERS);
