import { prisma } from '@/lib/prisma';
import { handler,reply,check,list,scope,HR,audit } from './http';
import { workingDates } from './calculations';
import { employeeView } from './serializers';
import { notifyEmployee } from './notifications';
const view=r=>({...r,employeeName:r.employee?employeeView(r.employee).name:undefined,typeName:r.timeOffType?.name,remainingAmount:r.remainingAmount!==undefined?Number(r.remainingAmount):undefined});
export const attendanceGET=handler(async({query,user,params})=>{const employeeId=scope(user,params.id||query.employeeId);return list('attendanceRecord',{...(employeeId?{employeeId}:{}),...(query.status?{status:query.status}:{}),...(query.fromDate?{date:{gte:new Date(query.fromDate),...(query.toDate?{lte:new Date(query.toDate)}:{})}}:{})},query,{employee:true},view);});
async function saveAttendance({request,user,params}) {
  const b=await request.json();const previous=params.id?await prisma.attendanceRecord.findUnique({where:{id:params.id}}):null;
  if(params.id){check(HR.includes(user.role),'Only HR may correct attendance',403);check(previous,'Attendance not found',404);check(String(b.reason||'').trim(),'A correction reason is required');}
  const employeeId=scope(user,b.employeeId||previous?.employeeId);check(employeeId,'Employee is required');
  const date=new Date(b.date);check(Number.isFinite(+date),'Valid date is required');date.setUTCHours(0,0,0,0);
  const employee=await prisma.employee.findUnique({where:{id:employeeId},include:{workingSchedule:{include:{scheduleDays:true}}}});check(employee,'Employee not found',404);
  const checkIn=b.checkIn?new Date(b.checkIn):null,checkOut=b.checkOut?new Date(b.checkOut):null,breakMinutes=Number(b.breakMinutes||0);
  check(!checkOut||checkIn,'Check-in is required before checkout');check(!checkIn||Number.isFinite(+checkIn),'Invalid check-in');check(!checkOut||Number.isFinite(+checkOut)&&checkOut>checkIn,'Checkout must follow check-in');
  const workedHours=checkIn&&checkOut?(checkOut-checkIn)/3600000-breakMinutes/60:0;check(breakMinutes>=0&&workedHours>=0,'Break duration exceeds attendance duration');
  const day=['SUNDAY','MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY'][date.getUTCDay()];const line=employee.workingSchedule?.scheduleDays.find(d=>d.dayOfWeek===day);
  const late=checkIn&&line?.startTime&&(checkIn.getUTCHours()*60+checkIn.getUTCMinutes()>line.startTime.getUTCHours()*60+line.startTime.getUTCMinutes());
  const status=!checkIn?'ABSENT':!checkOut?'EXCEPTION':late?'LATE':'PRESENT';
  const result=await prisma.$transaction(async tx=>{const data={employeeId,date,checkIn,checkOut,breakMinutes,workedHours,status,notes:b.notes||null,...(previous?{isManuallyCorrected:true,correctedByUserId:user.id}:{})};const row=previous?await tx.attendanceRecord.update({where:{id:params.id},data}):await tx.attendanceRecord.create({data});await audit(tx,user,previous?'CORRECT':'CREATE','ATTENDANCE',row.id,{before:previous,after:row,reason:b.reason||null});if(previous)await notifyEmployee(tx,employeeId,{type:'ATTENDANCE_UPDATED',title:'Attendance corrected',message:`${user.name} corrected your attendance for ${date.toISOString().slice(0,10)}.`,link:'/attendance'});return row;});return reply(result,previous?200:201);
}
export const attendancePOST=handler(saveAttendance),attendancePUT=handler(saveAttendance,HR);
export const attendanceDELETE=handler(async({params,user})=>{await prisma.$transaction(async tx=>{const before=await tx.attendanceRecord.delete({where:{id:params.id}});await audit(tx,user,'DELETE','ATTENDANCE',params.id,{before});});return reply({deleted:true});},HR);
export const typesGET=handler(async({query})=>list('timeOffType',{},query));
export const typesPOST=handler(async({request})=>{const b=await request.json();check(b.name&&b.code&&['DAYS','HOURS'].includes(b.unit),'Name, code and unit are required');return reply(await prisma.timeOffType.create({data:{name:b.name,code:b.code,unit:b.unit,requiresAllocation:b.requiresAllocation!==false,approvalRequired:true,payrollIntegration:true,isPaid:b.isPaid!==false}}),201);},HR);
export const allocationsGET=handler(async({query,user,params})=>{const employeeId=scope(user,params.id||query.employeeId);return list('timeOffAllocation',employeeId?{employeeId}:{},query,{employee:true,timeOffType:true},view);});
export const allocationsPOST=handler(async({request,user})=>{const b=await request.json();const start=new Date(b.periodStart),end=new Date(b.periodEnd),amount=Number(b.allocatedAmount);check(b.employeeId&&b.timeOffTypeId&&Number.isFinite(+start)&&end>=start&&amount>0,'Employee, leave type, valid period and positive allocation are required');const row=await prisma.$transaction(async tx=>{const existing=await tx.timeOffAllocation.findFirst({where:{employeeId:b.employeeId,timeOffTypeId:b.timeOffTypeId,status:'ACTIVE',periodStart:{lte:end},periodEnd:{gte:start}}});check(!existing,'An allocation already covers this period',409);const type=await tx.timeOffType.findUnique({where:{id:b.timeOffTypeId}});check(type,'Leave type not found',404);const row=await tx.timeOffAllocation.create({data:{employeeId:b.employeeId,timeOffTypeId:b.timeOffTypeId,periodStart:start,periodEnd:end,allocatedAmount:amount,takenAmount:0,remainingAmount:amount,status:'ACTIVE'}});await audit(tx,user,'ALLOCATE','TIME_OFF',row.id);await notifyEmployee(tx,b.employeeId,{type:'LEAVE_ALLOCATED',title:'Leave balance allocated',message:`${amount} ${type.unit.toLowerCase()} of ${type.name} were allocated to you.`,link:'/time-off/allocations'});return row;},{isolationLevel:'Serializable'});return reply(row,201);},HR);
export const requestsGET=handler(async({query,user,params})=>{const employeeId=scope(user,params.id||query.employeeId);return list('timeOffRequest',{...(employeeId?{employeeId}:{}),...(query.status?{status:query.status}:{})},query,{employee:true,timeOffType:true},view);});
export const requestsPOST=handler(async({request,user})=>{const b=await request.json(),employeeId=scope(user,b.employeeId);const start=new Date(b.fromDate),end=new Date(b.toDate);check(employeeId&&b.timeOffTypeId&&Number.isFinite(+start)&&end>=start&&b.reason,'Employee, leave type, valid dates and reason are required');const [employee,type]=await Promise.all([prisma.employee.findUnique({where:{id:employeeId},include:{workingSchedule:{include:{scheduleDays:true}}}}),prisma.timeOffType.findUnique({where:{id:b.timeOffTypeId}})]);check(employee?.workingSchedule&&type,'An assigned schedule and valid leave type are required');const dates=workingDates(start,end,employee.workingSchedule.scheduleDays);const duration=type.unit==='DAYS'?dates.length:dates.reduce((s,d)=>s+d.hours,0);check(duration>0,'No working time falls within these dates');return reply(await prisma.timeOffRequest.create({data:{employeeId,timeOffTypeId:type.id,fromDate:start,toDate:end,duration,reason:b.reason,status:'PENDING'}}),201);});
export const requestPUT=handler(async({request,user,params})=>{
  const b=await request.json();check(['APPROVED','REJECTED'].includes(b.status),'Choose approve or reject');
  const row=await prisma.$transaction(async tx=>{const r=await tx.timeOffRequest.findUnique({where:{id:params.id},include:{timeOffType:true}});check(r,'Request not found',404);check(r.status==='PENDING','This request was already processed',409);if(b.status==='APPROVED'){
    const overlap=await tx.timeOffRequest.findFirst({where:{employeeId:r.employeeId,status:'APPROVED',fromDate:{lte:r.toDate},toDate:{gte:r.fromDate}}});check(!overlap,'Approved leave overlaps this request',409);
    if(r.timeOffType.requiresAllocation&&r.timeOffType.isPaid){const a=await tx.timeOffAllocation.findFirst({where:{employeeId:r.employeeId,timeOffTypeId:r.timeOffTypeId,status:'ACTIVE',periodStart:{lte:r.fromDate},periodEnd:{gte:r.toDate}}});check(a,'No valid leave allocation');const updated=await tx.timeOffAllocation.updateMany({where:{id:a.id,remainingAmount:{gte:r.duration}},data:{remainingAmount:{decrement:r.duration},takenAmount:{increment:r.duration}}});check(updated.count===1,'Insufficient leave balance');}
  }const row=await tx.timeOffRequest.update({where:{id:r.id},data:{status:b.status,approvedByUserId:user.id,approvedAt:new Date(),rejectionReason:b.status==='REJECTED'?b.reason||'Refused by HR':null}});await audit(tx,user,b.status,'TIME_OFF',r.id);await notifyEmployee(tx,r.employeeId,{type:'LEAVE_REQUEST_UPDATED',title:`Leave request ${b.status.toLowerCase()}`,message:`${user.name} ${b.status.toLowerCase()} your ${r.timeOffType.name} request.`,link:'/time-off'});return row;},{isolationLevel:'Serializable'});return reply(row);
},HR);
