import { prisma } from '@/lib/prisma';
import { handler,reply,check,fail,list,scope,PAYROLL,MANAGERS,audit } from './http';
import { calculate,resolveContract,workingDates,money } from './calculations';
import { employeeView } from './serializers';
import { notifyEmployee } from './notifications';
const include={employees:{include:{employee:true}},payslips:{include:{employee:true,lines:{orderBy:{sequence:'asc'}}}},salaryStructure:true};
export function payslipView(p) {
  const e=p.snapshot?.employee||employeeView(p.employee),snapshot=p.snapshot||{};
  const lineView=l=>({...l,label:l.name,amount:Number(l.amount)});
  return {...p,...snapshot,employeeId:p.employeeId,employeeName:e.name,employeeEmail:e.email||p.employee?.email,employeeCode:e.employeeCode,department:e.department,jobPosition:e.jobPosition,designation:e.jobPosition,dateOfJoining:e.dateOfJoining,bankName:e.bankName,bankAccountNumber:e.bankAccountNumber,panNumber:e.panNumber,pfNumber:e.pfNumber,uanNumber:e.uanNumber,payslipNumber:`PS-${p.id.slice(-8).toUpperCase()}`,month:new Date(p.periodStart).getUTCMonth()+1,year:new Date(p.periodStart).getUTCFullYear(),paymentDate:p.paidAt||p.payrun?.paymentDate,earnings:p.lines.filter(l=>['BASIC','ALLOWANCE'].includes(l.category)).map(lineView),deductions:p.lines.filter(l=>l.category==='DEDUCTION').map(lineView),reimbursements:p.lines.filter(l=>l.category==='REIMBURSEMENT').map(lineView),grossEarnings:Number(p.grossEarnings),grossPay:Number(p.grossEarnings),totalDeductions:Number(p.grossDeductions),netPayable:Number(p.netPay),netPay:Number(p.netPay),netTransfer:Number(p.netTransfer),totalReimbursement:Number(p.totalReimbursement)};
}
export function payrunView(p) {
  const slips=p.payslips||[],computed=p.status!=='DRAFT';const sum=k=>computed?money(slips.reduce((n,s)=>n+Number(s[k]),0)):null;
  const totalGross=sum('grossEarnings'),totalDeductions=sum('grossDeductions'),totalNet=sum('netPay');
  return {...p,startDate:p.periodStart,endDate:p.periodEnd,month:new Date(p.periodStart).getUTCMonth()+1,year:new Date(p.periodStart).getUTCFullYear(),employeeCount:p.employees?.length||slips.length,totalGross,totalDeductions,totalNet,totals:{grossPay:totalGross,totalDeductions,netPay:totalNet},lines:(p.employees||[]).map(a=>{const s=slips.find(s=>s.employeeId===a.employeeId);const gross=s?Number(s.grossEarnings):null,deductions=s?Number(s.grossDeductions):null,net=s?Number(s.netPay):null;return {employeeId:a.employeeId,employeeName:employeeView(a.employee).name,department:a.employee.department,jobPosition:a.employee.designation,...s?.snapshot,basic:s?Number(s.lines.find(l=>l.code==='BASIC')?.amount||0):null,allowances:s?money(s.lines.filter(l=>l.category==='ALLOWANCE').reduce((n,l)=>n+Number(l.amount),0)):null,gross,grossPay:gross,deductions,totalDeductions:deductions,net,netPay:net,payslipId:s?.id||null};})};
}
function period(b){const start=new Date(b.startDate||b.periodStart),end=new Date(b.endDate||b.periodEnd);check(Number.isFinite(+start)&&Number.isFinite(+end)&&end>=start,'Select a valid payroll period');check((end-start)/86400000<370,'Payroll period must be less than one year');return {start,end};}
async function eligibleEmployees(client,{start,end,salaryStructureId,department,employeeType}) {
  const employees=await client.employee.findMany({where:{status:'ACTIVE',isArchived:false,...(department?{department}:{}),...(employeeType?{employeeType}:{})},include:{contracts:true,workingSchedule:true}});
  return employees.flatMap(employee=>{try{const contract=resolveContract(employee.contracts,start,end);return employee.workingSchedule&&contract.salaryStructureId===salaryStructureId?[{employee,contract}]:[];}catch{return [];}});
}
export const eligibleGET=handler(async({query})=>{const {start,end}=period(query);check(query.salaryStructureId,'Select a salary structure');const eligible=await eligibleEmployees(prisma,{start,end,salaryStructureId:query.salaryStructureId,department:query.department,employeeType:query.employeeType});return reply(eligible.map(({employee,contract})=>({...employeeView(employee),contractId:contract.id,contractWage:Number(contract.wage),salaryStructureId:contract.salaryStructureId,scheduleName:employee.workingSchedule.name})));},PAYROLL);
export const payrunsGET=handler(async({query})=>list('payrun',{...(query.status?{status:query.status}:{}),...(query.search?{name:{contains:query.search}}:{})},query,include,payrunView),PAYROLL);
export const payrunGET=handler(async({params})=>{const p=await prisma.payrun.findUnique({where:{id:params.id},include});check(p,'Payrun not found',404);return reply(payrunView(p));},PAYROLL);
export const payrunsPOST=handler(async({request,user})=>{const b=await request.json(),{start,end}=period(b);check(b.name&&b.salaryStructureId,'Select a salary structure');const p=await prisma.$transaction(async tx=>{let ids;if(b.selectionMode==='ALL_ELIGIBLE'){const eligible=await eligibleEmployees(tx,{start,end,salaryStructureId:b.salaryStructureId,department:b.department,employeeType:b.employeeType});ids=eligible.map(({employee})=>employee.id);}else{check(Array.isArray(b.employeeIds)&&b.employeeIds.length,'Select at least one employee');ids=[...new Set(b.employeeIds)];}check(ids.length,'No eligible employees were found for this period and salary structure');const employees=await tx.employee.findMany({where:{id:{in:ids},status:'ACTIVE',isArchived:false},include:{contracts:true,workingSchedule:true}});check(employees.length===ids.length,'Some selected employees are not eligible');for(const employee of employees){const contract=resolveContract(employee.contracts,start,end);check(employee.workingSchedule,'Employee is missing a working schedule');check(contract.salaryStructureId===b.salaryStructureId,'Employee contract uses a different salary structure');}const p=await tx.payrun.create({data:{name:b.name,salaryStructureId:b.salaryStructureId,periodStart:start,periodEnd:end,paymentDate:b.paymentDate?new Date(b.paymentDate):end,status:'DRAFT',createdByUserId:user.id,employees:{create:ids.map(employeeId=>({employeeId}))}},include});await audit(tx,user,'CREATE','PAYRUN',p.id,{selectionMode:b.selectionMode||'SPECIFIC_EMPLOYEES',employeeCount:ids.length});return p;},{isolationLevel:'Serializable'});return reply(payrunView(p),201);},PAYROLL);
async function action({request,user,params},kind) {
  const b=await request.json();check(Number.isInteger(b.expectedVersion),'Payrun version is required');
  const p=await prisma.$transaction(async tx=>{
    const p=await tx.payrun.findUnique({where:{id:params.id},include});check(p,'Payrun not found',404);
    if(p.version!==b.expectedVersion)fail('Payrun was changed by another session',409,'CONCURRENT_MODIFICATION',{currentVersion:p.version});
    const allowed={compute:['DRAFT','COMPUTED'],validate:['COMPUTED'],pay:['VALIDATED'],cancel:['DRAFT','COMPUTED','VALIDATED']}[kind];check(allowed.includes(p.status),'Action is not allowed in the current state',400,'INVALID_STATE');
    const claimed=await tx.payrun.updateMany({where:{id:p.id,version:b.expectedVersion},data:{version:{increment:1}}});check(claimed.count===1,'Payrun was changed by another session',409,'CONCURRENT_MODIFICATION');
    if(kind==='compute') {
      const structure=await tx.salaryStructure.findUnique({where:{id:p.salaryStructureId},include:{rules:true}});check(structure?.isActive,'Salary structure is inactive');
      for(const assignment of p.employees) {
        const e=await tx.employee.findUnique({where:{id:assignment.employeeId},include:{contracts:true,workingSchedule:{include:{scheduleDays:true}},attendanceRecords:{where:{date:{gte:p.periodStart,lte:p.periodEnd}}},timeOffRequests:{where:{status:'APPROVED',fromDate:{lte:p.periodEnd},toDate:{gte:p.periodStart}},include:{timeOffType:true}}}});
        let contract;try{contract=resolveContract(e.contracts,p.periodStart,p.periodEnd);}catch(error){fail(`${employeeView(e).name}: ${error.message}`,422,'CONTRACT_CONFLICT');}
        check(contract.salaryStructureId===p.salaryStructureId,'Contract salary structure changed; recreate this batch');check(e.workingSchedule,'Employee is missing a working schedule',422,'MISSING_SCHEDULE');
        const duplicate=await tx.payslip.findFirst({where:{employeeId:e.id,payrunId:{not:p.id},status:{not:'CANCELLED'},periodStart:{lte:p.periodEnd},periodEnd:{gte:p.periodStart}}});check(!duplicate,'Another payslip already covers this employee and period',409,'DUPLICATE_PAYSLIP');
        const dates=workingDates(p.periodStart,p.periodEnd,e.workingSchedule.scheduleDays);check(dates.length,'No working days in this period');
        let workedDays=0,paidLeaveDays=0,unpaidLeaveDays=0,missing=0,overtimeHours=0;
        for(const d of dates){const attendance=e.attendanceRecords.find(a=>a.date.toISOString().slice(0,10)===d.date);const leave=e.timeOffRequests.find(l=>l.fromDate.toISOString().slice(0,10)<=d.date&&l.toDate.toISOString().slice(0,10)>=d.date);if(leave){if(leave.timeOffType.isPaid)paidLeaveDays++;else unpaidLeaveDays++;}else if(attendance?.checkIn&&attendance?.checkOut){workedDays+=Math.min(1,Number(attendance.workedHours)/d.hours);overtimeHours+=Math.max(0,Number(attendance.workedHours)-d.hours);}else if(attendance?.status!=='ABSENT')missing++;}
        const result=calculate(structure.rules,{wage:Number(contract.wage),workedDays,workingDays:dates.length,payableDays:workedDays+paidLeaveDays,unpaidLeaveDays,overtimeHours});
        const snapshot={employee:employeeView(e),company:{name:process.env.COMPANY_NAME||'PeoplePay360',address:process.env.COMPANY_ADDRESS||'',taxId:process.env.COMPANY_TAX_ID||''},workingDays:dates.length,workedDays:missing?null:workedDays,paidLeaveDays,unpaidLeaveDays,lossOfPayDays:unpaidLeaveDays,attendanceStatus:missing?'PENDING_INPUT':'COMPLETE',missingAttendanceDays:missing,contractId:contract.id,contractWage:Number(contract.wage),structureName:structure.name};
        // Only identity and pay context are snapshotted, never unrelated employee records.
        delete snapshot.employee.contracts;delete snapshot.employee.attendanceRecords;delete snapshot.employee.timeOffRequests;delete snapshot.employee.workingSchedule;
        const values={periodStart:p.periodStart,periodEnd:p.periodEnd,workedDays,status:'COMPUTED',grossEarnings:result.grossEarnings,grossDeductions:result.totalDeductions,netPay:result.netPay,totalReimbursement:result.totalReimbursement,netTransfer:result.netTransfer,snapshot:JSON.parse(JSON.stringify(snapshot))};
        const slip=await tx.payslip.upsert({where:{payrunId_employeeId:{payrunId:p.id,employeeId:e.id}},create:{...values,payrunId:p.id,employeeId:e.id},update:values});await tx.payslipLine.deleteMany({where:{payslipId:slip.id}});await tx.payslipLine.createMany({data:result.lines.map(l=>({...l,payslipId:slip.id}))});
      }
    }
    if(kind==='validate') {
      const warnings=[],errors=[];check(p.payslips.length===p.employees.length,'Compute all selected employees first',422);
      for(const s of p.payslips){const base={employeeId:s.employeeId,employeeName:employeeView(s.employee).name};if(Number(s.netPay)<0)errors.push({...base,code:'NEGATIVE_NET_PAY',message:'Net pay cannot be negative'});if(s.snapshot?.attendanceStatus==='PENDING_INPUT')warnings.push({...base,code:'UNRECORDED_ATTENDANCE',message:'Attendance inputs are incomplete'});if(!s.employee.bankAccountNumber||!s.employee.bankIFSC)warnings.push({...base,code:'MISSING_BANK_ACCOUNT',message:'Bank details are incomplete'});if(!s.employee.pan)warnings.push({...base,code:'MISSING_PAN',message:'PAN is missing'});}
      if(errors.length)fail('Resolve blocking errors before validation',422,'VALIDATION_FAILED',{errors});if(warnings.length&&!b.acknowledgeWarnings)fail('Review and acknowledge payroll warnings',422,'WARNINGS_REQUIRE_ACKNOWLEDGMENT',{warnings});
      await audit(tx,user,'VALIDATE','PAYRUN',p.id,{warnings,acknowledged:!!b.acknowledgeWarnings});
    }
    const status={compute:'COMPUTED',validate:'VALIDATED',pay:'PAID',cancel:'CANCELLED'}[kind];
    await tx.payslip.updateMany({where:{payrunId:p.id},data:{status,...(kind==='pay'?{paidAt:new Date()}:{})}});
    if(kind==='pay')for(const s of p.payslips){await tx.payment.create({data:{payslipId:s.id,paymentMethod:'OTHER',paymentDate:p.paymentDate||new Date(),amount:s.netTransfer,status:'COMPLETED',notes:'Payment completion recorded; no bank transfer initiated.'}});await notifyEmployee(tx,s.employeeId,{type:'PAYSLIP_ISSUED',title:'Payslip available',message:`Your payslip for ${p.periodStart.toISOString().slice(0,7)} is ready.`,link:`/payroll/payslips/${s.id}`});}
    await audit(tx,user,kind.toUpperCase(),'PAYRUN',p.id,{from:p.status,to:status});return tx.payrun.update({where:{id:p.id},data:{status},include});
  },{isolationLevel:'Serializable',timeout:60000});return reply(payrunView(p));
}
export const computePOST=handler(x=>action(x,'compute'),PAYROLL),validatePOST=handler(x=>action(x,'validate'),MANAGERS),payPOST=handler(x=>action(x,'pay'),MANAGERS),cancelPOST=handler(x=>action(x,'cancel'),MANAGERS);
export const payslipsGET=handler(async({user,query})=>{check(user.role==='EMPLOYEE'||PAYROLL.includes(user.role),'Access denied',403);const employeeId=scope(user,query.employeeId);return list('payslip',{...(employeeId?{employeeId}:{}),...(user.role==='EMPLOYEE'?{status:'PAID'}:{}),...(query.payrunId?{payrunId:query.payrunId}:{}),...(query.department?{employee:{department:query.department}}:{})},query,{employee:true,lines:true,payrun:true},payslipView);});
export async function ownedPayslip(user,id) {check(user.role==='EMPLOYEE'||PAYROLL.includes(user.role),'Access denied',403);const p=await prisma.payslip.findUnique({where:{id},include:{employee:true,lines:{orderBy:{sequence:'asc'}},payrun:true}});check(p,'Payslip not found',404);scope(user,p.employeeId);if(user.role==='EMPLOYEE')check(p.status==='PAID','Payslip has not been issued',403);return p;}
export const payslipGET=handler(async({user,params})=>reply(payslipView(await ownedPayslip(user,params.id))));
