import {prisma} from '@/lib/prisma';
import {handler,reply,scope,PAYROLL,HR} from './http';
export const dashboardGET=handler(async({user,query})=>{
 const employeeId=scope(user,query.employeeId),employeeWhere={...(employeeId?{id:employeeId}:{}),...(query.department?{department:query.department}:{}),...(query.employeeType?{employeeType:query.employeeType}:{})};
 const employees=await prisma.employee.findMany({where:employeeWhere});const ids=employees.map(e=>e.id);
 const period=query.period?new Date(query.period+'-01'):null;const range=period?{gte:period,lt:new Date(Date.UTC(period.getUTCFullYear(),period.getUTCMonth()+1,1))}:undefined;
 const [attendance,leave,allocations,payslips,payruns]=await Promise.all([prisma.attendanceRecord.findMany({where:{employeeId:{in:ids},...(range?{date:range}:{})}}),prisma.timeOffRequest.findMany({where:{employeeId:{in:ids},...(range?{fromDate:range}:{})},include:{timeOffType:true}}),prisma.timeOffAllocation.findMany({where:{employeeId:{in:ids},status:'ACTIVE'}}),PAYROLL.includes(user.role)?prisma.payslip.findMany({where:{employeeId:{in:ids},status:'PAID',...(range?{periodStart:range}:{})},include:{employee:true}}):[],PAYROLL.includes(user.role)?prisma.payrun.findMany({orderBy:{createdAt:'desc'},take:5}):[]]);
 const count=s=>attendance.filter(a=>a.status===s).length;const totalNetSalaryPaid=payslips.reduce((n,s)=>n+Number(s.netPay),0);const departments=[...new Set(employees.map(e=>e.department))].map(name=>({name,department:name,headcount:employees.filter(e=>e.department===name).length,salary:payslips.filter(s=>s.employee.department===name).reduce((n,s)=>n+Number(s.netPay),0)}));
 const monthly=Object.entries(payslips.reduce((a,s)=>{const month=s.periodStart.toISOString().slice(0,7);a[month]=(a[month]||0)+Number(s.netPay);return a;},{})).sort().map(([month,netSalary])=>({month,netSalary}));
 return reply({kpis:{totalWorkforce:employees.length,totalNetSalaryPaid:PAYROLL.includes(user.role)?totalNetSalaryPaid:null,payslipsGenerated:payslips.length,averageSalary:payslips.length?totalNetSalaryPaid/payslips.length:0,approvedTimeOffDays:leave.filter(l=>l.status==='APPROVED'&&l.timeOffType.unit==='DAYS').reduce((n,l)=>n+Number(l.duration),0),attendanceHealth:{presentPercent:attendance.length?(count('PRESENT')+count('LATE'))/attendance.length*100:0,present:count('PRESENT')}},attendanceOverview:{present:count('PRESENT'),late:count('LATE'),absent:count('ABSENT'),exceptions:count('EXCEPTION'),missingCheckouts:attendance.filter(a=>a.checkIn&&!a.checkOut).length,manualEdits:attendance.filter(a=>a.isManuallyCorrected).length,coveragePercent:attendance.length?100:0},pendingTimeOffRequests:leave.filter(l=>l.status==='PENDING').length,leaveBalance:allocations.reduce((n,a)=>n+Number(a.remainingAmount),0),departmentBreakdown:departments,salaryByDepartment:departments,monthlySalaryTrend:monthly,recentPayruns:payruns,warnings:employees.filter(e=>!e.workingScheduleId).map(e=>({id:e.id,message:`${e.firstName} ${e.lastName}: no working schedule`,severity:'WARNING'}))});
});
export const usersGET=handler(async()=>reply(await prisma.user.findMany({select:{id:true,name:true,email:true,role:true,employeeId:true}})),['ADMIN']);
export const auditGET=handler(async()=>reply(await prisma.auditLog.findMany({orderBy:{createdAt:'desc'},take:200,include:{user:{select:{name:true}}}})),['ADMIN']);
