"use client";
import {useEffect,useState} from 'react';
import {apiClient} from '@/lib/api';
export function PayrunCreateModal({onClose,onSubmit,isLoading}){
 const [step,setStep]=useState(1),[structures,setStructures]=useState([]),[employees,setEmployees]=useState([]),[selected,setSelected]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [data,setData]=useState({name:'',salaryStructureId:'',startDate:'',endDate:'',paymentDate:'',department:'',employeeType:''});
 useEffect(()=>{apiClient.get('/api/salary-structures?limit=200&status=ACTIVE').then(r=>setStructures(r.data.data)).catch(e=>setError(e.response?.data?.message||'Unable to load structures'));},[]);
 const input=(name,label,type='text')=><label className="block text-sm">{label}<input required={!['department','employeeType','paymentDate'].includes(name)} type={type} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-3" value={data[name]} onChange={e=>setData({...data,[name]:e.target.value})}/></label>;
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{if(step===1){const r=await apiClient.get('/api/payruns/eligible-employees',{params:data});setEmployees(r.data.data);setSelected([]);setStep(2);}else{await onSubmit({...data,employeeIds:selected,selectionMode:'SPECIFIC_EMPLOYEES'});}}catch(e){setError(e.response?.data?.message||'Unable to continue');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="space-y-5"><h2 className="text-xl font-bold">{step===1?'1. Define payroll scope':'2. Select employees'}</h2>{step===1?<div className="grid gap-4 sm:grid-cols-2">{input('name','Payrun name')}<label>Salary structure<select required className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-3" value={data.salaryStructureId} onChange={e=>setData({...data,salaryStructureId:e.target.value})}><option value="">Select…</option>{structures.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{input('startDate','Period start','date')}{input('endDate','Period end','date')}{input('paymentDate','Planned payment date','date')}{input('department','Department filter')}</div>:<div className="space-y-3">{!employees.length&&<p>No eligible employees. Check active status, contract period and salary structure.</p>}{employees.map(e=><label className="flex gap-3 rounded-lg border border-slate-800 p-3" key={e.id}><input type="checkbox" checked={selected.includes(e.id)} onChange={event=>setSelected(event.target.checked?[...selected,e.id]:selected.filter(id=>id!==e.id))}/>{e.name} · {e.department}</label>)}</div>}{error&&<p role="alert" className="text-rose-400">{error}</p>}<div className="flex gap-4"><button disabled={busy||isLoading||step===2&&!selected.length} className="rounded-lg bg-violet-600 px-5 py-2 disabled:opacity-50">{busy||isLoading?'Working…':step===1?'Continue':'Create payrun'}</button>{step===2&&<button type="button" onClick={()=>setStep(1)}>Back</button>}<button type="button" onClick={onClose}>Cancel</button></div></form>;
}
