"use client";
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Grid3X3,List,Plus,Search,Users} from 'lucide-react';
import {useEmployeeStore} from '@/store/employeeStore';
import {useAuthStore} from '@/store/authStore';
import {EmployeeForm} from './EmployeeForm';
import {Badge} from '@/components/ui/Badge';
import {ErrorState} from '@/components/ui/ErrorState';
import {canAccessHR} from '@/lib/permissions';
const variant={ACTIVE:'success',NOTICE_PERIOD:'warning',TERMINATED:'danger'};
export default function UnifiedEmployeeDirectory(){
 const {user}=useAuthStore(),store=useEmployeeStore();const [view,setView]=useState('list'),[filters,setFilters]=useState({search:'',department:'',status:''}),[form,setForm]=useState(false),[message,setMessage]=useState('');
 const load=useCallback((retry=false)=>store.fetchEmployees(filters,retry),[filters,store.fetchEmployees]);useEffect(()=>{const id=setTimeout(load,300);return()=>clearTimeout(id);},[load]);
 const fields=['Employee','Contact','Role & department','Status'];
 async function save(data){await store.createEmployee(data);setForm(false);setMessage('Employee created successfully.');load();}
 if(form)return <div className="space-y-6"><h1 className="text-2xl font-bold">Add employee</h1><section className="rounded-2xl border border-slate-800 p-6"><EmployeeForm onSubmit={save} onCancel={()=>setForm(false)} isLoading={store.isSubmitting}/></section></div>;
 return <div className="space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Users/>Employee Master</h1><p className="text-slate-400">{store.total} records · central hub for HR activity</p></div>{canAccessHR(user?.role)&&<button onClick={()=>setForm(true)} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2"><Plus size={16}/>Add Employee</button>}</header>
 <section className="flex flex-wrap gap-3 rounded-xl border border-slate-800 bg-slate-900/60 p-3"><label className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3" size={16}/><input aria-label="Search employees" placeholder="Search name, code or email" className="w-full rounded-lg bg-slate-950 py-2.5 pl-9" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><input aria-label="Department" placeholder="Department" className="rounded-lg bg-slate-950 p-2.5" value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})}/><select aria-label="Status" className="rounded-lg bg-slate-950 p-2.5" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option><option>ACTIVE</option><option>NOTICE_PERIOD</option><option>TERMINATED</option></select><div className="flex rounded-lg border border-slate-700"><button aria-label="List view" className={`p-2 ${view==='list'?'bg-violet-600':''}`} onClick={()=>setView('list')}><List/></button><button aria-label="Kanban view" className={`p-2 ${view==='kanban'?'bg-violet-600':''}`} onClick={()=>setView('kanban')}><Grid3X3/></button></div></section>
 {message&&<p role="status" className="text-emerald-400">{message}</p>}{store.error&&<ErrorState title="Unable to load employees" message={store.error} onRetry={()=>load(true)}/>} {store.isLoading?<p>Loading employee records…</p>:!store.error&&!store.employees.length?<p className="rounded-xl border border-slate-800 p-8 text-center text-slate-400">No employee records match these filters.</p>:view==='kanban'?<div className="grid gap-5 lg:grid-cols-3">{['ACTIVE','NOTICE_PERIOD','TERMINATED'].map(status=><section key={status} className="rounded-xl border border-slate-800 bg-slate-900/50 p-4"><h2 className="mb-4 font-semibold">{status.replace('_',' ')} · {store.employees.filter(e=>e.employmentStatus===status).length}</h2><div className="space-y-3">{store.employees.filter(e=>e.employmentStatus===status).map(e=><Link href={`/employees/${e.id}`} key={e.id} className="block rounded-xl border border-slate-700 bg-slate-950 p-4 hover:border-violet-500"><b>{e.name}</b><p className="text-sm text-slate-400">{e.jobPosition} · {e.department}</p><p className="mt-2 text-xs">{e.email}</p></Link>)}</div></section>)}</div>:<div className="overflow-auto rounded-xl border border-slate-800"><table className="w-full text-left"><thead><tr>{fields.map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{store.employees.map(e=><tr className="border-t border-slate-800" key={e.id}><td className="p-4"><Link className="font-semibold text-violet-300" href={`/employees/${e.id}`}>{e.name}</Link><p className="text-xs text-slate-500">{e.employeeCode}</p></td><td className="p-4">{e.email}<p>{e.phone}</p></td><td className="p-4">{e.jobPosition}<p className="text-slate-500">{e.department}</p></td><td className="p-4"><Badge variant={variant[e.employmentStatus]}>{e.employmentStatus}</Badge></td></tr>)}</tbody></table></div>}</div>;
}
