import { requireAuth, isHr } from "@/lib/auth";
import { failure, handleError, success } from "@/lib/api";
import { NotFoundError } from "@/lib/errors";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
const day = z.object({ dayOfWeek: z.enum(["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]), startTime: z.string().regex(/^\d{2}:\d{2}$/), endTime: z.string().regex(/^\d{2}:\d{2}$/), breakMinutes: z.number().int().min(0), isWorking: z.boolean() });
const schema = z.object({ name: z.string().min(2), type: z.string().min(1), company: z.string().optional(), days: z.array(day).min(1) });
function hours(days) { const seen = new Set(); return days.reduce((total, item) => { if (seen.has(item.dayOfWeek)) throw new Error(`Duplicate schedule day: ${item.dayOfWeek}`); seen.add(item.dayOfWeek); if (!item.isWorking) return total; const [sh, sm] = item.startTime.split(":").map(Number); const [eh, em] = item.endTime.split(":").map(Number); const shift = eh * 60 + em - sh * 60 - sm; if (shift <= 0 || item.breakMinutes >= shift) throw new Error(`Invalid shift for ${item.dayOfWeek}`); return total + (shift - item.breakMinutes) / 60; }, 0); }
export async function GET(request, { params }) { try { const user = await requireAuth(); if (!isHr(user.role)) return failure("HR access is not allowed for this role", 403); const result = await prisma.workingSchedule.findUnique({ where: { id: (await params).id }, include: { days: true, employees: true } }); if (!result) throw new NotFoundError("Working schedule not found"); return success(result); } catch (error) { return handleError(error); } }
export async function PUT(request, { params }) { try { const user = await requireAuth(); if (!isHr(user.role)) return failure("HR access is not allowed for this role", 403); const id = (await params).id; const input = schema.parse(await request.json()); const result = await prisma.$transaction(async (tx) => { await tx.scheduleDay.deleteMany({ where: { workingScheduleId: id } }); return tx.workingSchedule.update({ where: { id }, data: { name: input.name, type: input.type, company: input.company, weeklyHours: hours(input.days), days: { create: input.days } }, include: { days: true } }); }); return success(result, "Working schedule updated"); } catch (error) { return handleError(error); } }
export async function DELETE(request, { params }) { try { const user = await requireAuth(); if (!isHr(user.role)) return failure("HR access is not allowed for this role", 403); const id = (await params).id; if (await prisma.employee.count({ where: { workingScheduleId: id } })) return failure("Working schedule is assigned to employees", 409); await prisma.workingSchedule.delete({ where: { id } }); return success(null, "Working schedule deleted"); } catch (error) { return handleError(error); } }
