import { requireAuth, isHr } from "@/lib/auth";
import { failure, handleError, success } from "@/lib/api";
import { BusinessRuleError } from "@/lib/errors";
import { audit } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

const decisionSchema = z.object({ status: z.enum(["APPROVED", "REJECTED"]) });
export async function PUT(request: Request, { params }: { params: Promise<{ id: string }> }) { try { const user = await requireAuth(); if (!isHr(user.role)) return failure("Only HR can approve time off", 403); const id = (await params).id; const input = decisionSchema.parse(await request.json()); const result = await prisma.$transaction(async (tx: any) => { const item = await tx.timeOffRequest.findUnique({ where: { id }, include: { timeOffType: true } }); if (!item) throw new BusinessRuleError("Time-off request not found"); if (item.status !== "PENDING") throw new BusinessRuleError("Only pending requests can be decided"); if (input.status === "REJECTED") return tx.timeOffRequest.update({ where: { id }, data: { status: "REJECTED", approvedByUserId: user.id, approvedAt: new Date() } }); if (item.timeOffType.requiresAllocation) { const allocation = await tx.timeOffAllocation.findFirst({ where: { employeeId: item.employeeId, timeOffTypeId: item.timeOffTypeId, periodStart: { lte: item.fromDate }, periodEnd: { gte: item.toDate }, status: "ACTIVE" } }); if (!allocation || Number(allocation.allocated) - Number(allocation.taken) < Number(item.duration)) throw new BusinessRuleError("Insufficient time-off allocation"); await tx.timeOffAllocation.update({ where: { id: allocation.id }, data: { taken: { increment: item.duration } } }); } return tx.timeOffRequest.update({ where: { id }, data: { status: "APPROVED", approvedByUserId: user.id, approvedAt: new Date() } }); }); await audit(user.id, `TIMEOFF_${input.status}`, "TIMEOFF_REQUEST", id); return success(result, `Time-off request ${input.status.toLowerCase()}`); } catch (error) { return handleError(error); } }
